# Generated by Django 5.2.4 on 2025-07-12 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='skills_offered',
            field=models.ManyToManyField(blank=True, related_name='users_offering', to='api.skill'),
        ),
        migrations.AddField(
            model_name='user',
            name='skills_wanted',
            field=models.ManyToManyField(blank=True, related_name='users_wanting', to='api.skill'),
        ),
    ]
